### ISSUE TITLE
移植coreclr 有计划日程

### ISSUE THREAD

**Issue by myFirstway** [theaoqi/coreclr#2]
对于移植coreclr 有计划日程吗？

**Comment by theaoqi** [comment]
感谢关注，目前尚无明确日程，预计2020年推出。

**Comment by theaoqi** [comment]
> 对于移植coreclr 有计划日程吗？

感谢关注，目前尚无明确日程，预计2020年推出。

**Comment by myFirstway** [comment]
> > 对于移植coreclr 有计划日程吗？
> 
> 感谢关注，目前尚无明确日程，预计2020年推出。

谢谢，期待.net core能够完美的跑在龙芯上

**Comment by NMSAzulX** [comment]
期待~  ❤🧡💛💚💙💜🤎🖤🤍💖

**Comment by nluyan** [comment]
强烈期待啊
