### ISSUE TITLE
进展如何。

### ISSUE THREAD

**Issue by pkingwsd** [theaoqi/coreclr#3]
各位好：
真心关切这个项目，我从DOTNET社区了解到这个项目，并且了解.NET CORE3 已经通过了HELLO WORLD.  真是一个好消息。  不知道没有具体一些的时间点，或大至的计划。

**Comment by jinyuttt** [comment]
同上

**Comment by theaoqi** [comment]
https://github.com/dotnet/runtime/issues/4234#issuecomment-629930924 @pkingwsd @jinyuttt
